In [1]:
import numpy as np
import math
from typing import List, Callable

In [2]:
def sigmoid(s) -> float:
  
  """
  This function gets the s (out of the last layer * weights) parameter
  And pass it for relu function
  """
  return 1 / (1 + np.exp(-s))

def deri_sigmoid(s:float) -> float:
  return s * (1 - s)

In [3]:
def MSE(y_hat:np.array, y:np.array):
    y_hat = np.array([y_hat])
    y = np.array([y])
    return (1/(2*y_hat.shape[0]))*sum([(y_hat[i] - y[i])**2 for i in range(y_hat.shape[0])])

In [4]:
x1 = np.array([0.5, 0.1])
y1 = 0.7
x2 = np.array([0.2, 0.6])
y2 = 0.8
pesos1 = np.array([[0.5, 0.2], [0.6,-0.1],[-0.4, -0.3]])
pesos2 = np.array([0.7, -0.1, 0.2])

In [41]:
class NN:


    def __init__(self, layers:List[dict], lr:float=0.01) -> None:
        
        self.layers = layers
        self.lr = lr
        self.loss = 0


    def forward(self, x:np.array) -> None:
        
        for layer in self.layers:
            s = np.dot(layer["weights"], x) + layer["bias"]
            x = layer["activation_func"](s)
            print(f"O out é {x}")
            print(f"O shape de out é {x.shape}")
            layer["out"] = x
    

    def compute_loss(self, y_hat:np.array, y:np.array, loss_func:Callable=MSE) -> None:

        self.loss = loss_func(y_hat, y)
    

    def backward(self, X, y) -> None:

        for i in range(len(self.layers)-1, -1, -1):
            if i == (len(self.layers) - 1):
                d_J_o = self.layers[i]["out"] - y
                d_o_s = self.layers[i]["out"] * (1 - self.layers[i]["out"])
                self.layers[i]["delta"] = d_J_o * d_o_s
                self.layers[i]["d_J"] = np.dot(self.layers[i]["delta"], self.layers[i-1]["out"].reshape(-1, self.layers[i-1]["out"].shape[0]))
            elif i == 0:
                d_o_s = self.layers[i]["out"] * (1 - self.layers[i]["out"])
                self.layers[i]["delta"] = np.dot(self.layers[i+1]["weights"].reshape(-1, self.layers[i+1]["weights"].shape[0]), self.layers[i+1]["delta"]) * d_o_s
                self.layers[i]["d_J"] = np.dot(X, self.layers[i]["delta"].reshape(-1, self.layers[i]["delta"].shape[0]))
            else:
                d_o_s = self.layers[i]["out"] * (1 - self.layers[i]["out"])
                self.layers[i]["delta"] = np.dot(self.layers[i+1]["weights"], self.layers[i+1]["delta"]) * d_o_s
                self.layers[i]["d_J"] = np.dot(self.layers[i-1]["out"], self.layers[i]["delta"])


    def optimizer(self):

        for layer in self.layers:
            print(layer["d_J"])
            layer["weights"] = layer["weights"] - (self.lr * layer["d_J"])


    def train(self, X, y, epochs):

        for epoch in range(0, epochs):
            print(epoch)
            # print(self.layers[-1].get("out",None))
            self.forward(X)
            # print(X)
            # print(epoch)
            # print(self.layers[-1].get("out",None))
            self.compute_loss(self.layers[-1]["out"], y)
            self.backward(X, y)
            self.optimizer()
            # print("-"*100)
            # print(f"{' '*40}EPOCH: {epoch}")
            # print("-"*100)
            # print(f'Loss {self.loss}')
        

In [42]:
x1 = np.array([[0.5, 0.1]]).T
y1 = 0.7
pesos1 = np.array([[0.5, 0.2], [0.6,-0.1],[-0.4, -0.3]])
pesos2 = np.array([[0.7, -0.1, 0.2]])

In [43]:
nn = NN([{"weights":pesos1, "bias":0, "activation_func":sigmoid}, {"weights":pesos2, "bias":0, "activation_func":sigmoid}])
nn.train(x1, y1, 10)

0
O out é [[0.5670929 ]
 [0.57199613]
 [0.44275215]]
O shape de out é (3, 1)
O out é [[0.60547144]]
O shape de out é (1, 1)
d_o_s [[0.23887578]]
delta layer 1 [[-0.02258058]]
d_J layer 1 [[-0.01280529 -0.01291601 -0.0099976 ]]
d_o_s [[0.24549854]
 [0.24481656]
 [0.24672268]]
delta layer 0 [[-0.00388045]
 [ 0.00055281]
 [-0.00111423]]
d_J layer 0 [[-1.94022514e-03  2.76405039e-04 -5.57114222e-04]
 [-3.88045028e-04  5.52810078e-05 -1.11422844e-04]]
[[-1.94022514e-03  2.76405039e-04 -5.57114222e-04]
 [-3.88045028e-04  5.52810078e-05 -1.11422844e-04]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [151]:
nn.layers[-1]["out"]

array([0.6065971 , 0.60659751, 0.6065865 ])